name: Build and Deploy
on: # ç›‘å¬ main åˆ†æ”¯ä¸Šçš„ push äº‹ä»¶
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # æ„å»ºç¯å¢ƒä½¿ç”¨ ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: add node env
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install and Dev
        run: |
          npm install
          npm run prd

      - name: Deploy ğŸš€ #
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./ # The folder the action should deploy.
          BRANCH: gh-pages
          ACCESS_TOKEN: ${{ secrets.DOCSAPI }} # VUE_ADMIN_TEMPLATE æ˜¯æˆ‘çš„ secret åç§°ï¼Œéœ€è¦æ›¿æ¢æˆä½ çš„


      # - name: Deploy # å°†æ‰“åŒ…å†…å®¹å‘å¸ƒåˆ° github page
      #   uses: JamesIves/github-pages-deploy-action@3.5.9 # ä½¿ç”¨åˆ«äººå†™å¥½çš„ actions
      #   with: # è‡ªå®šä¹‰ç¯å¢ƒå˜é‡
      #     ACCESS_TOKEN: ${{ secrets.DOCSAPI }} # VUE_ADMIN_TEMPLATE æ˜¯æˆ‘çš„ secret åç§°ï¼Œéœ€è¦æ›¿æ¢æˆä½ çš„
      #     BRANCH: main
      #     # FOLDER: ./
      #     REPOSITORY_NAME: wfppfw/docsApi # è¿™æ˜¯æˆ‘çš„ github page ä»“åº“
      #     #TARGET_FOLDER: github-actions-demo # æ‰“åŒ…çš„æ–‡ä»¶å°†æ”¾åˆ°é™æ€æœåŠ¡å™¨ github-actions-demo ç›®å½•ä¸‹
