name: Build and Deploy
on: # 监听 main 分支上的 push 事件
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: add node env
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install and Dev
        run: |
          npm install
          npm run prd

      - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@3.5.9 # 使用别人写好的 actions
        with: # 自定义环境变量
          ACCESS_TOKEN: ${{ secrets.DOCSAPI }} # VUE_ADMIN_TEMPLATE 是我的 secret 名称，需要替换成你的
          BRANCH: main
          FOLDER: ./
          REPOSITORY_NAME: wfppfw/docsApi # 这是我的 github page 仓库
          #TARGET_FOLDER: github-actions-demo # 打包的文件将放到静态服务器 github-actions-demo 目录下
